<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
		<LangVersion>latest</LangVersion>
		<TargetFramework>net10.0</TargetFramework>
		<Authors>Eshava</Authors>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="FakeItEasy" Version="9.0.1" />
		<PackageReference Include="FluentAssertions" Version="[7.0.0]" />
		<PackageReference Include="MSTest.TestAdapter" Version="4.1.0" />
		<PackageReference Include="MSTest.TestFramework" Version="4.1.0" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.3.0" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Eshava.Storm.Linq\Eshava.Storm.Linq.csproj" />
	</ItemGroup>
</Project>
