using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using Eshava.Storm.Dialects;
using Eshava.Storm.Extensions;
using Eshava.Storm.MetaData.Enums;

namespace Eshava.Storm.MetaData.Models
{
	internal class Entity : AbstractEntity
	{
		internal Entity(Type type, ConfigurationSource configurationSource) : base(type, configurationSource)
		{

		}

		/// <summary>
		/// The schema as configured, without quotes; empty when the table is named without one
		/// </summary>
		public string Schema { get; private set; }

		/// <summary>
		/// The table as configured, without quotes
		/// </summary>
		public string Table { get; private set; }

		/// <summary>
		/// The table name as SQL, quoted in the current dialect
		/// </summary>
		public string TableName => Table.IsNullOrEmpty() ? null : SqlDialects.Current.QuoteTableName(Schema, Table);

		public void SetTable(string schema, string table)
		{
			Schema = schema;
			Table = table;
		}

		public bool HasPrimaryKey()
		{
			return Properties.Values.Any(p => p.IsPrimaryKey);
		}

		public bool HasAutoGeneratedPrimaryKey()
		{
			var primaryKeys = Properties.Values.Where(p => p.IsPrimaryKey && p.AutoGeneratedOption != DatabaseGeneratedOption.None);

			return primaryKeys.Count() == 1;
		}

		public Property GetFirstPrimaryKey()
		{
			return Properties.Values.First(p => p.IsPrimaryKey);
		}
	}}