using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Eshava.Storm.Attributes;
using Eshava.Storm.Enums;
using Eshava.Storm.Extensions;
using Eshava.Storm.Handler;
using Eshava.Storm.IntegrationTests.Infrastructure;
using FluentAssertions;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Npgsql;

namespace Eshava.Storm.IntegrationTests
{
	[TestClass]
	public sealed class BulkInsertTests
	{
		[ClassInitialize]
		public static void ClassInitialize(TestContext context)
		{
			new TagTypeHandler().AddTypeHandler();
		}

		[TestMethod]
		public async Task ManyRowsOfEveryTypeTest()
		{
			// Arrange
			await using var connection = await CreateShipmentTableAsync();
			var shipments = Enumerable.Range(1, 1000).Select(CreateShipment).ToList();

			// Act
			await connection.BulkInsertAsync(shipments);
			var count = await connection.ExecuteScalarAsync<long>("SELECT count(*) FROM shipments");
			var first = await connection.QueryEntityAsync<Shipment>(1);
			var last = await connection.QueryEntityAsync<Shipment>(1000);

			// Assert
			count.Should().Be(1000);
			first.Should().BeEquivalentTo(shipments[0], options => options.Excluding(shipment => shipment.Picked));
			first.Picked.Should().Be(new DateTime(2026, 9, 25, 8, 0, 0, DateTimeKind.Utc));
			// The mapper creates an owned object also when its columns are NULL
			last.Destination.Street.Should().BeNull();
			last.Destination.City.Should().BeNull();
			last.Tag.Value.Should().Be("tag-1000");
		}

		[TestMethod]
		public async Task GeneratedKeyIsLeftToTheDatabaseTest()
		{
			// Arrange
			await using var connection = await PostgreSqlDatabase.OpenAsync(
				"DROP TABLE IF EXISTS parcels",
				"CREATE TABLE parcels (id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, label text NOT NULL)"
			);

			// Act
			await connection.BulkInsertAsync(new[] { new Parcel { Label = "a" }, new Parcel { Label = "b" } });
			var ids = await connection.QueryAsync<int>("SELECT id FROM parcels ORDER BY id");

			// Assert
			ids.Should().Equal(1, 2);
		}

		[TestMethod]
		public async Task RolledBackTransactionLeavesNoRowTest()
		{
			// Arrange
			await using var connection = await CreateShipmentTableAsync();

			// Act
			await using (var transaction = await connection.BeginTransactionAsync())
			{
				await connection.BulkInsertAsync(new[] { CreateShipment(1) }, transaction);
				await transaction.RollbackAsync();
			}

			var count = await connection.ExecuteScalarAsync<long>("SELECT count(*) FROM shipments");

			// Assert
			count.Should().Be(0);
		}

		[TestMethod]
		public async Task CustomTableNameAndClosedConnectionTest()
		{
			// Arrange
			await using var connection = await CreateShipmentTableAsync("DROP TABLE IF EXISTS shipments_archive", "CREATE TABLE shipments_archive (LIKE shipments)");
			await connection.CloseAsync();

			// Act
			await connection.BulkInsertAsync(new[] { CreateShipment(1) }, "shipments_archive");
			var stateAfter = connection.State;
			await connection.OpenAsync();
			var count = await connection.ExecuteScalarAsync<long>("SELECT count(*) FROM shipments_archive");

			// Assert
			stateAfter.Should().Be(ConnectionState.Closed);
			count.Should().Be(1);
		}

		[TestMethod]
		public async Task WithoutThePostgreSqlDialectItIsRefusedTest()
		{
			// Arrange
			await using var connection = await CreateShipmentTableAsync();
			Settings.Dialect = SqlDialect.SqlServer;

			try
			{
				// Act
				var bulkInsert = () => connection.BulkInsertAsync(new[] { CreateShipment(1) });

				// Assert
				await bulkInsert.Should().ThrowAsync<InvalidOperationException>();
			}
			finally
			{
				Settings.Dialect = SqlDialect.PostgreSql;
			}
		}

		private static Task<NpgsqlConnection> CreateShipmentTableAsync(params string[] statements)
		{
			return PostgreSqlDatabase.OpenAsync(new[]
			{
				"DROP TABLE IF EXISTS shipments_archive",
				"DROP TABLE IF EXISTS shipments",
				"""
				CREATE TABLE shipments (
					id bigint PRIMARY KEY,
					reference uuid NOT NULL,
					weight numeric(18, 3) NOT NULL,
					pieces smallint NOT NULL,
					status int NOT NULL,
					fragile boolean NOT NULL,
					shipped date NOT NULL,
					picked timestamptz NOT NULL,
					delivered timestamptz NULL,
					planned timestamp NULL,
					label bytea NULL,
					tag text NULL,
					destination_street text NULL,
					destination_city text NULL
				)
				"""
			}.Concat(statements).ToArray());
		}

		private static Shipment CreateShipment(int id)
		{
			return new Shipment
			{
				Id = id,
				Reference = Guid.NewGuid(),
				Weight = 12.5m + id,
				Pieces = 3,
				Status = ShipmentStatus.Shipped,
				Fragile = id % 2 == 0,
				Shipped = new DateOnly(2026, 9, 25),
				// Without kind, as a value read from somewhere often is: written as UTC into timestamptz
				Picked = new DateTime(2026, 9, 25, 8, 0, 0),
				Delivered = new DateTimeOffset(2026, 9, 26, 10, 0, 0, TimeSpan.FromHours(2)),
				Planned = new DateTime(2026, 9, 24, 7, 30, 0, DateTimeKind.Utc),
				Label = [0x01, (byte)(id % 256)],
				Tag = new Tag($"tag-{id}"),
				Destination = id == 1000 ? null : new Address { Street = "Main", City = "Springfield" }
			};
		}

		private enum ShipmentStatus
		{
			Created = 1,
			Shipped = 2
		}

		[Table("Shipments")]
		private class Shipment
		{
			public long Id { get; set; }
			public Guid Reference { get; set; }
			public decimal Weight { get; set; }
			public int Pieces { get; set; }
			public ShipmentStatus Status { get; set; }
			public bool Fragile { get; set; }
			public DateOnly Shipped { get; set; }
			public DateTime Picked { get; set; }
			public DateTimeOffset? Delivered { get; set; }
			public DateTime? Planned { get; set; }
			public byte[] Label { get; set; }
			public Tag Tag { get; set; }

			[OwnsOne]
			public Address Destination { get; set; }
		}

		private class Address
		{
			public string Street { get; set; }
			public string City { get; set; }
		}

		private class Parcel
		{
			[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
			public int Id { get; set; }

			public string Label { get; set; }
		}

		private sealed class Tag
		{
			public Tag(string value)
			{
				Value = value;
			}

			public string Value { get; }
		}

		private class TagTypeHandler : StringTypeHandler<Tag>
		{
			protected override string Format(Tag tag)
			{
				return tag.Value;
			}

			protected override Tag Parse(string value)
			{
				return new Tag(value);
			}
		}
	}
}