using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Threading.Tasks;
using Eshava.Storm.Attributes;
using Eshava.Storm.IntegrationTests.Infrastructure;
using FluentAssertions;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace Eshava.Storm.IntegrationTests
{
	[TestClass]
	public sealed class CrudTests
	{
		[TestMethod]
		public async Task InsertReturnsTheGeneratedKeyTest()
		{
			// Arrange
			await using var connection = await PostgreSqlDatabase.OpenAsync(
				"DROP TABLE IF EXISTS counters",
				"CREATE TABLE counters (id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name text NOT NULL)"
			);

			// Act
			var first = await connection.InsertAsync<Counter, int>(new Counter { Name = "first" });
			var second = await connection.InsertAsync<Counter, int>(new Counter { Name = "second" });

			// Assert
			first.Should().Be(1);
			second.Should().Be(2);
		}

		[TestMethod]
		public async Task ValuesOfEveryTypeMakeTheRoundTripTest()
		{
			// Arrange
			await using var connection = await CreateProductTableAsync();
			var product = CreateProduct();

			// Act
			var id = await connection.InsertAsync<Product, Guid>(product);
			var result = await connection.QueryEntityAsync<Product>(id);

			// Assert
			id.Should().Be(product.Id);
			result.Should().BeEquivalentTo(product);
		}

		[TestMethod]
		public async Task UpdatePartialPatchAndDeleteTest()
		{
			// Arrange
			await using var connection = await CreateProductTableAsync();
			var product = CreateProduct();
			await connection.InsertAsync<Product, Guid>(product);

			// Act
			product.Name = "updated";
			var updated = await connection.UpdateAsync(product);
			var partial = await connection.UpdatePartialAsync<Product>(new { product.Id, Price = 9.5m });
			var patched = await connection.UpdatePatchAsync<Product>(new[]
			{
				new KeyValuePair<string, object>(nameof(Product.Id), product.Id),
				new KeyValuePair<string, object>(nameof(Product.IsActive), false)
			});
			var afterUpdates = await connection.QueryEntityAsync<Product>(product.Id);
			var deleted = await connection.DeleteAsync(product);
			var afterDelete = await connection.QueryEntityAsync<Product>(product.Id);

			// Assert
			updated.Should().BeTrue();
			partial.Should().BeTrue();
			patched.Should().BeTrue();
			afterUpdates.Name.Should().Be("updated");
			afterUpdates.Price.Should().Be(9.5m);
			afterUpdates.IsActive.Should().BeFalse();
			deleted.Should().BeTrue();
			afterDelete.Should().BeNull();
		}

		[TestMethod]
		public async Task ColumnNamedWithReservedWordTest()
		{
			// Arrange
			await using var connection = await PostgreSqlDatabase.OpenAsync(
				"DROP TABLE IF EXISTS steps",
				"CREATE TABLE steps (\"order\" int PRIMARY KEY, name text NOT NULL)"
			);

			// Act
			await connection.InsertAsync<Step, int>(new Step { Position = 1, Name = "first" });
			var updated = await connection.UpdateAsync(new Step { Position = 1, Name = "changed" });
			var result = await connection.QueryEntityAsync<Step>(1);

			// Assert
			updated.Should().BeTrue();
			result.Name.Should().Be("changed");
		}

		[TestMethod]
		public async Task OwnedObjectTest()
		{
			// Arrange
			await using var connection = await PostgreSqlDatabase.OpenAsync(
				"DROP TABLE IF EXISTS residents",
				"CREATE TABLE residents (id int PRIMARY KEY, home_street text NULL, home_city text NULL)"
			);

			// Act
			await connection.InsertAsync<Resident, int>(new Resident { Id = 1, Home = new Address { Street = "Main", City = "Springfield" } });
			var result = await connection.QueryEntityAsync<Resident>(1);

			// Assert
			result.Home.Street.Should().Be("Main");
			result.Home.City.Should().Be("Springfield");
		}

		private static Task<Npgsql.NpgsqlConnection> CreateProductTableAsync()
		{
			return PostgreSqlDatabase.OpenAsync(
				"DROP TABLE IF EXISTS products",
				"""
				CREATE TABLE products (
					id uuid PRIMARY KEY,
					name text NOT NULL,
					price numeric(18, 4) NOT NULL,
					isactive boolean NOT NULL,
					colour int NOT NULL,
					day date NULL,
					scheduled timestamptz NULL,
					created timestamptz NOT NULL,
					payload bytea NULL
				)
				"""
			);
		}

		private static Product CreateProduct()
		{
			return new Product
			{
				Id = Guid.NewGuid(),
				Name = "product",
				Price = 12.3456m,
				IsActive = true,
				Colour = Colour.Blue,
				Day = new DateOnly(2026, 9, 25),
				Scheduled = new DateTimeOffset(2026, 9, 25, 10, 30, 0, TimeSpan.FromHours(2)),
				Created = new DateTime(2026, 9, 25, 8, 0, 0, DateTimeKind.Utc),
				Payload = [0x01, 0x02, 0x03]
			};
		}

		private enum Colour
		{
			Red = 1,
			Blue = 2
		}

		private class Counter
		{
			[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
			public int Id { get; set; }

			public string Name { get; set; }
		}

		private class Product
		{
			public Guid Id { get; set; }
			public string Name { get; set; }
			public decimal Price { get; set; }
			public bool IsActive { get; set; }
			public Colour Colour { get; set; }
			public DateOnly? Day { get; set; }
			public DateTimeOffset? Scheduled { get; set; }
			public DateTime Created { get; set; }
			public byte[] Payload { get; set; }
		}

		private class Step
		{
			[Key]
			[Column("Order")]
			public int Position { get; set; }

			public string Name { get; set; }
		}

		private class Resident
		{
			public int Id { get; set; }

			[OwnsOne]
			public Address Home { get; set; }
		}

		private class Address
		{
			public string Street { get; set; }
			public string City { get; set; }
		}
	}
}