using System.Reflection;

namespace Eshava.Storm.Models
{
	internal class KeyProperty
	{
		public PropertyInfo PropertyInfo { get; set; }
		public bool AutoGenerated { get; set; }
		public string ColumnName { get; set; }

		/// <summary>
		/// The name of the key property, which is also the name its value has in a patch
		/// </summary>
		public string PropertyName { get; set; }
	}
}