using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using Eshava.Storm.Interfaces;
using Eshava.Storm.MetaData.Models;

namespace Eshava.Storm.Engines
{
	internal class PostgreSqlCRUDCommandEngine : AbstractCRUDCommandEngine, ICRUDCommandEngine
	{
		public PostgreSqlCRUDCommandEngine(
			IObjectGenerator objectGenerator
		) : base(objectGenerator)
		{
		}

		protected override string GetLastInsertedPrimaryKeyQuery() => "SELECT lastval();";

		/// <summary>
		/// The insert itself returns the generated key, which does not depend on the sequence behind the column
		/// </summary>
		protected override void AppendGeneratedPrimaryKeyQuery(StringBuilder sql, Entity entity)
		{
			var generatedKey = entity
				.GetProperties()
				.First(property => property.IsPrimaryKey && property.AutoGeneratedOption != DatabaseGeneratedOption.None);

			sql.Append(" RETURNING ");
			sql.Append(QuoteIdentifier(generatedKey.ColumnName));
			sql.AppendLine(";");
		}
	}
}